<?php
/**
 * Invoice Ninja (https://quoteninja.com).
 *
 * @link https://github.com/quoteninja/quoteninja source repository
 *
 * @copyright Copyright (c) 2022. Invoice Ninja LLC (https://quoteninja.com)
 *
 * @license https://www.elastic.co/licensing/elastic-license
 */

namespace App\Import\Definitions;

class QuoteMap
{
    public static function importable()
    {
        return [
            0 => 'quote.number',
            1 => 'quote.user_id',
            2 => 'quote.amount',
            3 => 'quote.balance',
            4 => 'client.name',
            5 => 'quote.discount',
            6 => 'quote.po_number',
            7 => 'quote.date',
            8 => 'quote.due_date',
            9 => 'quote.terms',
            10 => 'quote.status',
            11 => 'quote.public_notes',
            12 => 'quote.is_sent',
            13 => 'quote.private_notes',
            14 => 'quote.uses_inclusive_taxes',
            15 => 'quote.tax_name1',
            16 => 'quote.tax_rate1',
            17 => 'quote.tax_name2',
            18 => 'quote.tax_rate2',
            19 => 'quote.tax_name3',
            20 => 'quote.tax_rate3',
            21 => 'quote.is_amount_discount',
            22 => 'quote.footer',
            23 => 'quote.partial',
            24 => 'quote.partial_due_date',
            25 => 'quote.custom_value1',
            26 => 'quote.custom_value2',
            27 => 'quote.custom_value3',
            28 => 'quote.custom_value4',
            29 => 'quote.custom_value5',
            30 => 'quote.custom_value6',
            31 => 'quote.custom_value7',
            32 => 'quote.custom_value8',
            33 => 'quote.custom_surcharge1',
            34 => 'quote.custom_surcharge2',
            35 => 'quote.custom_surcharge3',
            36 => 'quote.custom_surcharge4',
            37 => 'quote.exchange_rate',
            38 => 'payment.date',
            39 => 'payment.amount',
            40 => 'payment.transaction_reference',
            41 => 'item.quantity',
            42 => 'item.cost',
            43 => 'item.product_key',
            44 => 'item.notes',
            45 => 'item.discount',
            46 => 'item.is_amount_discount',
            47 => 'item.tax_name1',
            48 => 'item.tax_rate1',
            49 => 'item.tax_name2',
            50 => 'item.tax_rate2',
            51 => 'item.tax_name3',
            52 => 'item.tax_rate3',
            53 => 'item.custom_value1',
            54 => 'item.custom_value2',
            55 => 'item.custom_value3',
            56 => 'item.custom_value4',
            57 => 'item.custom_value5',
            58 => 'item.custom_value6',
            59 => 'item.custom_value7',
            60 => 'item.custom_value8',
            61 => 'item.type_id',
            62 => 'client.email',
        ];
    }

    public static function import_keys()
    {
        return [
            0 => 'texts.quote_number',
            1 => 'texts.user',
            2 => 'texts.amount',
            3 => 'texts.balance',
            4 => 'texts.client',
            5 => 'texts.discount',
            6 => 'texts.po_number',
            7 => 'texts.date',
            8 => 'texts.due_date',
            9 => 'texts.terms',
            10 => 'texts.status',
            11 => 'texts.public_notes',
            12 => 'texts.sent',
            13 => 'texts.private_notes',
            14 => 'texts.uses_inclusive_taxes',
            15 => 'texts.tax_name',
            16 => 'texts.tax_rate',
            17 => 'texts.tax_name',
            18 => 'texts.tax_rate',
            19 => 'texts.tax_name',
            20 => 'texts.tax_rate',
            21 => 'texts.is_amount_discount',
            22 => 'texts.footer',
            23 => 'texts.partial',
            24 => 'texts.partial_due_date',
            25 => 'texts.custom_value1',
            26 => 'texts.custom_value2',
            27 => 'texts.custom_value3',
            28 => 'texts.custom_value4',
            29 => 'texts.custom_value5',
            30 => 'texts.custom_value6',
            31 => 'texts.custom_value7',
            32 => 'texts.custom_value8',
            33 => 'texts.surcharge',
            34 => 'texts.surcharge',
            35 => 'texts.surcharge',
            36 => 'texts.surcharge',
            37 => 'texts.exchange_rate',
            38 => 'texts.payment_date',
            39 => 'texts.payment_amount',
            40 => 'texts.transaction_reference',
            41 => 'texts.quantity',
            42 => 'texts.cost',
            43 => 'texts.product_key',
            44 => 'texts.notes',
            45 => 'texts.discount',
            46 => 'texts.is_amount_discount',
            47 => 'texts.tax_name',
            48 => 'texts.tax_rate',
            49 => 'texts.tax_name',
            50 => 'texts.tax_rate',
            51 => 'texts.tax_name',
            52 => 'texts.tax_rate',
            53 => 'texts.custom_value',
            54 => 'texts.custom_value',
            55 => 'texts.custom_value',
            56 => 'texts.custom_value',
            57 => 'texts.custom_value',
            58 => 'texts.custom_value',
            59 => 'texts.custom_value',
            60 => 'texts.custom_value',
            61 => 'texts.type',
            62 => 'texts.email',
        ];
    }
}
