<?php
/**
 * Invoice Ninja (https://invoiceninja.com).
 *
 * @link https://github.com/invoiceninja/invoiceninja source repository
 *
 * @copyright Copyright (c) 2025. Invoice Ninja LLC (https://invoiceninja.com)
 *
 * @license https://www.elastic.co/licensing/elastic-license
 */

namespace App\Import\Definitions;

class RecurringInvoiceMap
{
    public static function importable()
    {
        return [
            0 => 'invoice.number',
            1 => 'invoice.user_id',
            2 => 'invoice.amount',
            3 => 'invoice.balance',
            4 => 'client.name',
            5 => 'invoice.discount',
            6 => 'invoice.po_number',
            7 => 'invoice.next_send_date',
            8 => 'invoice.due_date',
            9 => 'invoice.terms',
            10 => 'invoice.status',
            11 => 'invoice.public_notes',
            12 => 'invoice.is_sent',
            13 => 'invoice.private_notes',
            14 => 'invoice.uses_inclusive_taxes',
            15 => 'invoice.tax_name1',
            16 => 'invoice.tax_rate1',
            17 => 'invoice.tax_name2',
            18 => 'invoice.tax_rate2',
            19 => 'invoice.tax_name3',
            20 => 'invoice.tax_rate3',
            21 => 'invoice.is_amount_discount',
            22 => 'invoice.footer',
            23 => 'invoice.partial',
            24 => 'invoice.partial_due_date',
            25 => 'invoice.custom_value1',
            26 => 'invoice.custom_value2',
            27 => 'invoice.custom_value3',
            28 => 'invoice.custom_value4',
            29 => 'invoice.custom_value5',
            30 => 'invoice.custom_value6',
            31 => 'invoice.custom_value7',
            32 => 'invoice.custom_value8',
            33 => 'invoice.custom_surcharge1',
            34 => 'invoice.custom_surcharge2',
            35 => 'invoice.custom_surcharge3',
            36 => 'invoice.custom_surcharge4',
            37 => 'invoice.exchange_rate',
            38 => 'invoice.frequency_id',
            39 => 'invoice.remaining_cycles',
            40 => 'invoice.auto_bill',
            41 => 'payment.date',
            42 => 'payment.amount',
            43 => 'payment.transaction_reference',
            44 => 'item.quantity',
            45 => 'item.cost',
            46 => 'item.product_key',
            47 => 'item.notes',
            48 => 'item.discount',
            49 => 'item.is_amount_discount',
            50 => 'item.tax_name1',
            51 => 'item.tax_rate1',
            52 => 'item.tax_name2',
            53 => 'item.tax_rate2',
            54 => 'item.tax_name3',
            55 => 'item.tax_rate3',
            56 => 'item.custom_value1',
            57 => 'item.custom_value2',
            58 => 'item.custom_value3',
            59 => 'item.custom_value4',
            60 => 'item.custom_value5',
            61 => 'item.custom_value6',
            62 => 'item.custom_value7',
            63 => 'item.custom_value8',
            64 => 'item.type_id',
            65 => 'client.email',
        ];
    }

    public static function import_keys()
    {
        return [
            0 => 'texts.invoice_number',
            1 => 'texts.user',
            2 => 'texts.amount',
            3 => 'texts.balance',
            4 => 'texts.client',
            5 => 'texts.discount',
            6 => 'texts.po_number',
            7 => 'texts.start_date',
            8 => 'texts.due_date',
            9 => 'texts.terms',
            10 => 'texts.status',
            11 => 'texts.public_notes',
            12 => 'texts.sent',
            13 => 'texts.private_notes',
            14 => 'texts.uses_inclusive_taxes',
            15 => 'texts.tax_name',
            16 => 'texts.tax_rate',
            17 => 'texts.tax_name',
            18 => 'texts.tax_rate',
            19 => 'texts.tax_name',
            20 => 'texts.tax_rate',
            21 => 'texts.is_amount_discount',
            22 => 'texts.footer',
            23 => 'texts.partial',
            24 => 'texts.partial_due_date',
            25 => 'texts.custom_value1',
            26 => 'texts.custom_value2',
            27 => 'texts.custom_value3',
            28 => 'texts.custom_value4',
            29 => 'texts.custom_value5',
            30 => 'texts.custom_value6',
            31 => 'texts.custom_value7',
            32 => 'texts.custom_value8',
            33 => 'texts.surcharge',
            34 => 'texts.surcharge',
            35 => 'texts.surcharge',
            36 => 'texts.surcharge',
            37 => 'texts.exchange_rate',
            38 => 'texts.frequency_id',
            39 => 'texts.remaining_cycles',
            40 => 'texts.auto_bill',
            41 => 'texts.payment_date',
            42 => 'texts.payment_amount',
            43 => 'texts.transaction_reference',
            44 => 'texts.quantity',
            45 => 'texts.cost',
            46 => 'texts.product_key',
            47 => 'texts.notes',
            48 => 'texts.discount',
            49 => 'texts.is_amount_discount',
            50 => 'texts.tax_name',
            51 => 'texts.tax_rate',
            52 => 'texts.tax_name',
            53 => 'texts.tax_rate',
            54 => 'texts.tax_name',
            55 => 'texts.tax_rate',
            56 => 'texts.custom_value',
            57 => 'texts.custom_value',
            58 => 'texts.custom_value',
            59 => 'texts.custom_value',
            60 => 'texts.custom_value',
            61 => 'texts.custom_value',
            62 => 'texts.custom_value',
            63 => 'texts.custom_value',
            64 => 'texts.type',
            65 => 'texts.email',
        ];
    }
}
